//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crea_CaSdkComercial {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int IntervalSeconds {
            get {
                return ((int)(this["IntervalSeconds"]));
            }
            set {
                this["IntervalSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Compac\\COMERCIAL")]
        public string RutaSistema {
            get {
                return ((string)(this["RutaSistema"]));
            }
            set {
                this["RutaSistema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Compac\\Empresas\\")]
        public string RutaEmpresas {
            get {
                return ((string)(this["RutaEmpresas"]));
            }
            set {
                this["RutaEmpresas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CONTPAQ I COMERCIAL")]
        public string NombreSistema {
            get {
                return ((string)(this["NombreSistema"]));
            }
            set {
                this["NombreSistema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adSDKDemo")]
        public string Empresas {
            get {
                return ((string)(this["Empresas"]));
            }
            set {
                this["Empresas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AplicacionId {
            get {
                return ((int)(this["AplicacionId"]));
            }
            set {
                this["AplicacionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnviarEmail {
            get {
                return ((bool)(this["EnviarEmail"]));
            }
            set {
                this["EnviarEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S3y0$sd1@.18")]
        public string PasswordLlavePrivada {
            get {
                return ((string)(this["PasswordLlavePrivada"]));
            }
            set {
                this["PasswordLlavePrivada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supervisor")]
        public string UsuarioContpaq {
            get {
                return ((string)(this["UsuarioContpaq"]));
            }
            set {
                this["UsuarioContpaq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Nextcloud\\Crea_CaSdkComercial\\Log\\")]
        public string LogEjecucion {
            get {
                return ((string)(this["LogEjecucion"]));
            }
            set {
                this["LogEjecucion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entrega Documento Pago")]
        public string CuerpoCorreo {
            get {
                return ((string)(this["CuerpoCorreo"]));
            }
            set {
                this["CuerpoCorreo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Crea_4\\Crea_CaSdk_Comercial\\Layout\\Layout_SDK_NC.xlsx")]
        public string PathLayoutRecurrente {
            get {
                return ((string)(this["PathLayoutRecurrente"]));
            }
            set {
                this["PathLayoutRecurrente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pem@bideli.mx")]
        public string ReplyTo {
            get {
                return ((string)(this["ReplyTo"]));
            }
            set {
                this["ReplyTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pedro Escobas")]
        public string NameReplyTo {
            get {
                return ((string)(this["NameReplyTo"]));
            }
            set {
                this["NameReplyTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Compac\\Empresas\\#BASEDATOS#\\XML_SDK\\")]
        public string PathArchivos {
            get {
                return ((string)(this["PathArchivos"]));
            }
            set {
                this["PathArchivos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PasswordContpaq {
            get {
                return ((string)(this["PasswordContpaq"]));
            }
            set {
                this["PasswordContpaq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database=#BASEDATOS#;Server=10.10.15.60\\crea;Integrated Security=False;User ID=sa" +
            ";Password=crea4.0#17")]
        public string ConnectionStringContpaq {
            get {
                return ((string)(this["ConnectionStringContpaq"]));
            }
            set {
                this["ConnectionStringContpaq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Crea 4.0")]
        public string SenderName {
            get {
                return ((string)(this["SenderName"]));
            }
            set {
                this["SenderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("facturacion@buzon-cfdi.mx")]
        public string SenderEmail {
            get {
                return ((string)(this["SenderEmail"]));
            }
            set {
                this["SenderEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database=crea_Sdk;Server=10.73.10.20\\crea;Integrated Security=False;User ID=sa;Pa" +
            "ssword=crea4.0#17")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
    }
}
